google_key: <%= ENV.fetch('GOOGLE_MAP_API_KEY') %>
keystation_endpoint: <%= ENV.fetch('KS_ENDPOINT') %>
keyreserve_partner_token: <%= ENV.fetch('KS_PARTNER_TOKEN') %>
ks_checkin_endpoint: <%= ENV.fetch('KS_CHECKIN_ENDPOINT') %>

