google_key: <%= ENV.fetch('GOOGLE_MAP_API_KEY') %>
# TODO Change keyreserve partner' token
keyreserve_partner_token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoia2V5cmVzZXJ2ZV9wYXJ0bmVyIiwiY3JlYXRlZF9hdCI6IjIwMTgvMDIvMjcgMTU6MTQiLCJwYXJ0bmVyIjp0cnVlfQ.Yq3gO1_Fkz8hbcRDkogqRVDMdG1ARBr01T8m5BWAY80'

